name: bible
description: A new Flutter application.

version: 3.0.0+3

environment:
  #sdk: ">=2.1.0 <3.0.0"
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.14
  flutter_tts: ^3.8.5
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0
  fluttertoast: ^8.2.1
  confirm_dialog: 1.0.2
  flutter_markdown: ^0.6.19
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - images/
  - images/books/
  - images/angels/
  - icon/
  - assets/
flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true
